/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'visa' : IDL.Null,
  'immigrationLaw' : IDL.Null,
  'study' : IDL.Null,
  'employment' : IDL.Null,
  'citizenship' : IDL.Null,
});
export const Time = IDL.Int;
export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : Time,
  'author' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : Category,
});
export const Booking = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'serviceInterest' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const ContactInquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const Testimonial = IDL.Record({
  'service' : IDL.Text,
  'review' : IDL.Text,
  'country' : IDL.Text,
  'name' : IDL.Text,
  'rating' : IDL.Nat8,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTestimonial' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createConsultationBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createContactInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
  'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getAllConsultations' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
  'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
  'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text],
      [IDL.Bool],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'visa' : IDL.Null,
    'immigrationLaw' : IDL.Null,
    'study' : IDL.Null,
    'employment' : IDL.Null,
    'citizenship' : IDL.Null,
  });
  const Time = IDL.Int;
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : Time,
    'author' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : Category,
  });
  const Booking = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'serviceInterest' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const ContactInquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const Testimonial = IDL.Record({
    'service' : IDL.Text,
    'review' : IDL.Text,
    'country' : IDL.Text,
    'name' : IDL.Text,
    'rating' : IDL.Nat8,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTestimonial' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat8, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createConsultationBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createContactInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'deleteBlogPost' : IDL.Func([IDL.Nat], [], []),
    'getAllBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getAllConsultations' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(ContactInquiry)], ['query']),
    'getAllTestimonials' : IDL.Func([], [IDL.Vec(Testimonial)], ['query']),
    'getBlogPost' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, Category, IDL.Text],
        [IDL.Bool],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };